displayName=MLM activity timer
author=micro
description=Adds a timer in Motherlode Mine showing how long you've been mining a vein.
tags=timer,mlm,motherlode,motherload,mine,paydirt,pay-dirt,activity,idle,afk,tick,tock,ticktock
version=1.0
plugins=com.mlmactivity.MlmActivityPlugin
build=standard