displayName=Slayer History
author=micro
support=https://github.com/samszotkowski/runelite-plugins/tree/slayer-history
description=Log and display Slayer tasks
tags=slayer,history,track,log,task
plugins=com.slayerhistory.SlayerHistoryPlugin